#%RAML 1.0 NamedExample

{
    "emp_id": 100,
    "emp_fullName": "Abiy Ahmed",
    "emp_gender": "M",
    "emp_salary": 16000,
    "emp_department": "HRM",
    "emp_dob": "1985-10-10",
    "is_active": true
} 
